version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile:  Dockerfile.prod
    container_name: mern-docker-with-test-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - mern-docker-with-tests-network

  api:
    build: ./api
    container_name: mern-docker-with-test-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
      - JWR_SECRET=SECRET_KEY
    depends_on:
      - api_db
    networks:
      - mern-docker-with-tests-network

  auth:
    build: ./auth
    container_name: mern-docker-with-test-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - JWR_SECRET=SECRET_KEY
    depends_on:
      - auth_db
    networks:
      - mern-docker-with-tests-network

  api_db:
    image: mongo:latest
    container_name: mern-docker-with-test-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - mern-docker-with-tests-network

  auth_db:
    image: mongo:latest
    container_name: mern-docker-with-test-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - mern-docker-with-tests-network

  nginx:
    image: nginx:stable-alpine
    container_name: mern-docker-with-test-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - mern-docker-with-tests-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  mern-docker-with-tests-network:
    driver: bridge